apiVersion: v1
kind: Service
metadata:
  name: okteto92
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "okteto92"
    port: 8080
  selector:
    app: okteto92
